### ISSUE TITLE
Some visual representation on GUI

### ISSUE THREAD

**Issue by NuwanJ** [Pera-Swarm/visualizer#37]
It is better if we can have some representation on followings in the swarm server

- [ ] Communications 
    - [ ] Simple (server triggered > incoming, Robot triggered > outgoing)
    - [ ] Directional (server triggered > incoming, Robot triggered > outgoing)
- [x] Sensor Readings
   - [x] Distance (server triggered)
   - [x] Color (server triggered)
   - [ ] Proximity (server triggered)
- [x] Robot Status  (robot triggered or query request)

@luk3Sky @DDilshani please comment your ideas here

Current suggestions
- A collapsable panel (like in here https://threejs.org/editor/ )
- alert kind popups for subscribed messages

**Comment by luk3Sky** [comment]
I think we should look at this representation from the visualizer perspective. There are 3 things we need to address in my opinion.

#### 1. Robot snapshot
This should request a snapshot of robot attributes from the swarm server including coordinates (latest), sensor readings, realm info, (robot state) pattern formation info in a short description manner.
This should be addressed in a management protocol.

#### 2. Obstacle controller
The Visualizer should be able to change the obstacles in the virtual environment and send the updated info to the swarm server and get back the validated (env limitations & other validations) response.

#### 3. Logging
This can be made available in the swarm admin with respect to administration and authority issue.

I'm currently working on a setup like this [example](https://threejs.org/examples/?q=Stat#webgl_geometry_spline_editor). And add your thoughts also. @NuwanJ @DDilshani 

### Find the proposed management protocols from [here](https://docs.google.com/document/u/1/d/e/2PACX-1vTm_0MmPGw8-B8v63e-Jc8sfDNO9txeNVYmvAswR7ti8Glnw_4Wqmm6OpOiHOp8b9D15OUumNXIjC5y/pub)

**Comment by NuwanJ** [comment]
1. MQTT protocols (*mgt/*) seems to be ok. 
2. Let's hold the *Live Obstacle Update* feature for a while since we have a higher priority on implementing swarm algorithms
3. Logging: Yes, I also think we must implement a lightweight (H/W) logging channel for robots

**Comment by NuwanJ** [comment]
Introduced robot snapshots
